

export const companies = [
  { abrev: "AAPL", name: "Apple Inc.", commonName: "Apple", link: "https://www.apple.com", logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg" },
  { abrev: "TSLA", name: "Tesla, Inc.", commonName: "Tesla", link: "https://www.tesla.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png" },
  { abrev: "AMZN", name: "Amazon.com, Inc.", commonName: "Amazon", link: "https://www.amazon.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg" },
  { abrev: "MSFT", name: "Microsoft Corporation", commonName: "Microsoft", link: "https://www.microsoft.com", logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo_2022.svg" },
  { abrev: "NVDA", name: "NVIDIA Corporation", commonName: "NVIDIA", link: "https://www.nvidia.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/21/NVIDIA_logo.svg" },
  { abrev: "GOOGL", name: "Alphabet Inc.", commonName: "Google", link: "https://www.abc.xyz", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png" },
  { abrev: "META", name: "Meta Platforms, Inc.", commonName: "Meta", link: "https://about.fb.com", logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Meta_Platforms_Logo.svg" },
  { abrev: "NFLX", name: "Netflix, Inc.", commonName: "Netflix", link: "https://www.netflix.com", logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg" },
  { abrev: "JPM", name: "JPMorgan Chase & Co.", commonName: "JPMorgan", link: "https://www.jpmorganchase.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a4/J.P._Morgan_logo.svg" },
  { abrev: "V", name: "Visa Inc.", commonName: "Visa", link: "https://www.visa.com", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Visa_2014_logo.svg" },
  { abrev: "BAC", name: "Bank of America Corporation", commonName: "Bank of America", link: "https://www.bankofamerica.com", logo: "https://www.wikicorporates.org/mediawiki/images/thumb/9/92/Bank-of-America-2018.svg/1000px-Bank-of-America-2018.svg.png" },
  { abrev: "AMD", name: "Advanced Micro Devices, Inc.", commonName: "AMD", link: "https://www.amd.com", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0d/AMD_logo_2012.svg" },
  { abrev: "PYPL", name: "PayPal Holdings, Inc.", commonName: "PayPal", link: "https://www.paypal.com", logo: "https://upload.wikimedia.org/wikipedia/commons/6/69/PayPal_logo_2014.svg" },
  { abrev: "DIS", name: "The Walt Disney Company", commonName: "Disney", link: "https://www.thewaltdisneycompany.com", logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/The_Walt_Disney_Company_logo.svg" },
  { abrev: "T", name: "AT&T Inc.", commonName: "AT&T", link: "https://www.att.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/AT%26T_logo_2016.svg" },
  { abrev: "PFE", name: "Pfizer Inc.", commonName: "Pfizer", link: "https://www.pfizer.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pfizer_logo_2019.svg" },
  { abrev: "COST", name: "Costco Wholesale Corporation", commonName: "Costco", link: "https://www.costco.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Costco_Wholesale_logo.svg" },
  { abrev: "INTC", name: "Intel Corporation", commonName: "Intel", link: "https://www.intel.com", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Intel_logo_%282020%29.svg" },
  { abrev: "KO", name: "The Coca-Cola Company", commonName: "Coca-Cola", link: "https://www.coca-colacompany.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Coca-Cola_logo_2019.svg" },
  { abrev: "TGT", name: "Target Corporation", commonName: "Target", link: "https://www.target.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Target_logo.svg" },
  { abrev: "NKE", name: "NIKE, Inc.", commonName: "Nike", link: "https://www.nike.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_of_Nike.svg" },
  { abrev: "SPY", name: "SPDR S&P 500 ETF Trust", commonName: "SPDR", link: "https://www.ssga.com/us/en/institutional/etfs/funds/spdr-s-p-500-etf-trust-spy", logo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/SPDR_S%26P_500_ETF_Trust_logo.png" },
  { abrev: "BA", name: "The Boeing Company", commonName: "Boeing", link: "https://www.boeing.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Boeing_logo_2016.svg" },
  { abrev: "BABA", name: "Alibaba Group Holding Limited", commonName: "Alibaba", link: "https://www.alibabagroup.com", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Alibaba_group_logo.svg" },
  { abrev: "XOM", name: "Exxon Mobil Corporation", commonName: "ExxonMobil", link: "https://corporate.exxonmobil.com", logo: "https://upload.wikimedia.org/wikipedia/commons/7/73/Exxon_Mobil_Logo_2017.svg" },
  { abrev: "WMT", name: "Walmart Inc.", commonName: "Walmart", link: "https://www.walmart.com", logo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Walmart_logo_2020.svg" },
  { abrev: "GE", name: "General Electric Company", commonName: "GE", link: "https://www.ge.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ec/General_Electric_logo_2016.svg" },
  { abrev: "CSCO", name: "Cisco Systems, Inc.", commonName: "Cisco", link: "https://www.cisco.com", logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/Cisco_logo.svg" },
  { abrev: "VZ", name: "Verizon Communications Inc.", commonName: "Verizon", link: "https://www.verizon.com", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Verizon_2015_logo.svg" },
  { abrev: "JNJ", name: "Johnson & Johnson", commonName: "Johnson & Johnson", link: "https://www.jnj.com", logo: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Johnson_&_Johnson_logo_2021.svg" },
  { abrev: "CVX", name: "Chevron Corporation", commonName: "Chevron", link: "https://www.chevron.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Chevron_logo.svg" },
  { abrev: "PLTR", name: "Palantir Technologies Inc.", commonName: "Palantir", link: "https://www.palantir.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Palantir_logo.svg" },
  { abrev: "SQ", name: "Block, Inc.", commonName: "Block", link: "https://www.block.xyz", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Block_logo.svg" },
  { abrev: "SHOP", name: "Shopify Inc.", commonName: "Shopify", link: "https://www.shopify.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/96/Shopify_logo_2020.svg" },
  { abrev: "SBUX", name: "Starbucks Corporation", commonName: "Starbucks", link: "https://www.starbucks.com", logo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Starbucks_Logo_2020.png" },
  { abrev: "SOFI", name: "SoFi Technologies, Inc.", commonName: "SoFi", link: "https://www.sofi.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/96/SoFi_logo.svg" },
  { abrev: "HOOD", name: "Robinhood Markets, Inc.", commonName: "Robinhood", link: "https://www.robinhood.com", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Robinhood_Logo.svg" },
  { abrev: "RBLX", name: "Roblox Corporation", commonName: "Roblox", link: "https://www.roblox.com", logo: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Roblox_logo_2021.svg" },
  { abrev: "SNAP", name: "Snap Inc.", commonName: "Snapchat", link: "https://www.snap.com", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Snap_Inc._logo.svg" },
  { abrev: "UBER", name: "Uber Technologies, Inc.", commonName: "Uber", link: "https://www.uber.com", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Uber_Logo_2018.svg" },
  { abrev: "FDX", name: "FedEx Corporation", commonName: "FedEx", link: "https://www.fedex.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/FedEx_Express_logo_2016.svg" },
  { abrev: "ABBV", name: "AbbVie Inc.", commonName: "AbbVie", link: "https://www.abbvie.com", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/AbbVie_Logo.svg" },
  { abrev: "ETSY", name: "Etsy, Inc.", commonName: "Etsy", link: "https://www.etsy.com", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Etsy_logo_2017.svg" },
  { abrev: "MRNA", name: "Moderna, Inc.", commonName: "Moderna", link: "https://www.modernatx.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Moderna_logo.svg" },  { abrev: "GM", name: "General Motors Company", link: "https://investor.gm.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/General_Motors_logo_2016.svg" },
  { abrev: "GM", name: "General Motors Company", commonName: "GM", link: "https://investor.gm.com", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/General_Motors_logo_2016.svg" },
  { abrev: "F", name: "Ford Motor Company", commonName: "Ford", link: "https://www.ford.com", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Ford_Motor_Company_logo_2017.svg" },
  { abrev: "RIVN", name: "Rivian Automotive, Inc.", commonName: "Rivian", link: "https://www.rivian.com", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Rivian_logo.svg" },
  { abrev: "LCID", name: "Lucid Group, Inc.", commonName: "Lucid", link: "https://www.lucidmotors.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Lucid_Motors_logo.svg" },
  { abrev: "CCL", name: "Carnival Corporation & plc", commonName: "Carnival", link: "https://www.carnivalcorp.com", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Carnival_Corp_logo.svg" },
  { abrev: "DAL", name: "Delta Air Lines, Inc.", commonName: "Delta", link: "https://www.delta.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Delta_Air_Lines_logo.svg" },
  { abrev: "UAL", name: "United Airlines Holdings, Inc.", commonName: "United Airlines", link: "https://www.united.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/United_Airlines_logo.svg" },
  { abrev: "AAL", name: "American Airlines Group Inc.", commonName: "American Airlines", link: "https://www.aa.com", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f0/American_Airlines_logo_2013.svg" },
  { abrev: "TSM", name: "Taiwan Semiconductor Manufacturing Company Limited", commonName: "TSMC", link: "https://www.tsmc.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/22/Taiwan_Semiconductor_Manufacturing_Company_logo.svg" },
  { abrev: "SONY", name: "Sony Group Corporation", commonName: "Sony", link: "https://www.sony.com", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Sony_logo_2021.svg" },
  { abrev: "ET", name: "Energy Transfer LP", commonName: "Energy Transfer", link: "https://www.energytransfer.com", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Energy_Transfer_logo.svg" },
  { abrev: "NOK", name: "Nokia Corporation", commonName: "Nokia", link: "https://www.nokia.com", logo: "https://upload.wikimedia.org/wikipedia/commons/8/89/Nokia_logo_2021.svg" },
  { abrev: "MRO", name: "Marathon Oil Corporation", commonName: "Marathon Oil", link: "https://www.marathonoil.com", logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Marathon_Oil_logo.svg" },
  { abrev: "COIN", name: "Coinbase Global, Inc.", commonName: "Coinbase", link: "https://www.coinbase.com", logo: "https://upload.wikimedia.org/wikipedia/commons/8/84/Coinbase_logo.svg" },
  { abrev: "SIRI", name: "Sirius XM Holdings Inc.", commonName: "SiriusXM", link: "https://www.siriusxm.com", logo: "https://upload.wikimedia.org/wikipedia/commons/4/47/Sirius_XM_logo_2021.svg" },
  { abrev: "RIOT", name: "Riot Platforms, Inc.", commonName: "Riot", link: "https://www.riotplatforms.com", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Riot_Blocks_logo.svg" },
  { abrev: "CPRX", name: "Catalyst Pharmaceuticals, Inc.", commonName: "Catalyst Pharma", link: "https://www.catalystpharma.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Catalyst_Pharmaceuticals_logo.svg/1200px-Catalyst_Pharmaceuticals_logo.svg.png" },
  { abrev: "VWO", name: "Vanguard FTSE Emerging Markets ETF", commonName: "Vanguard Emerging Markets", link: "https://www.vanguard.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vanguard_logo.svg/1200px-Vanguard_logo.svg.png" },
  { abrev: "SPYG", name: "SPDR Portfolio S&P 500 Growth ETF", commonName: "SPDR Growth", link: "https://www.ssga.com/us/en/institutional/etfs/funds/spdr-portfolio-s-p-500-growth-etf-spyg", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/SPDR_logo.svg/1200px-SPDR_logo.svg.png" },
  { abrev: "ROKU", name: "Roku, Inc.", commonName: "Roku", link: "https://www.roku.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Roku_logo.svg/1200px-Roku_logo.svg.png"},
  { abrev: "VIAC", name: "Paramount Global", commonName: "Paramount", link: "https://www.paramount.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Paramount_Global_logo.svg/1200px-Paramount_Global_logo.svg.png" },
{ abrev: "ATVI", name: "Activision Blizzard, Inc.", commonName: "Activision Blizzard", link: "https://www.activisionblizzard.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Activision_Blizzard_logo.svg/1200px-Activision_Blizzard_logo.svg.png" },
{ abrev: "BIDU", name: "Baidu, Inc.", commonName: "Baidu", link: "https://www.baidu.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Baidu_logo.svg/1200px-Baidu_logo.svg.png" },
{ abrev: "DOCU", name: "DocuSign, Inc.", commonName: "DocuSign", link: "https://www.docusign.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/DocuSign_logo.svg/1200px-DocuSign_logo.svg.png" },
{ abrev: "ZM", name: "Zoom Video Communications, Inc.", commonName: "Zoom", link: "https://www.zoom.us", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Zoom_communications_logo.svg/1200px-Zoom_communications_logo.svg.png" },
{ abrev: "PINS", name: "Pinterest, Inc.", commonName: "Pinterest", link: "https://www.pinterest.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Pinterest_logo.svg/1200px-Pinterest_logo.svg.png" },
{ abrev: "TLRY", name: "Tilray Brands, Inc.", commonName: "Tilray", link: "https://www.tilray.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Tilray_logo.svg/1200px-Tilray_logo.svg.png" },
{ abrev: "WBA", name: "Walgreens Boots Alliance, Inc.", commonName: "Walgreens", link: "https://www.walgreensbootsalliance.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Walgreens_Boots_Alliance_logo.svg/1200px-Walgreens_Boots_Alliance_logo.svg.png" },
{ abrev: "MGM", name: "MGM Resorts International", commonName: "MGM", link: "https://www.mgmresorts.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/MGM_Resorts_logo.svg/1200px-MGM_Resorts_logo.svg.png" },
{ abrev: "NIO", name: "NIO Inc.", commonName: "NIO", link: "https://www.nio.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/NIO_logo.svg/1200px-NIO_logo.svg.png" },
{ abrev: "C", name: "Citigroup Inc.", commonName: "Citigroup", link: "https://www.citigroup.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Citigroup_logo.svg/1200px-Citigroup_logo.svg.png" },
{ abrev: "GS", name: "The Goldman Sachs Group, Inc.", commonName: "Goldman Sachs", link: "https://www.goldmansachs.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Goldman_Sachs_logo.svg/1200px-Goldman_Sachs_logo.svg.png" },
{ abrev: "WFC", name: "Wells Fargo & Company", commonName: "Wells Fargo", link: "https://www.wellsfargo.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Wells_Fargo_logo.svg/1200px-Wells_Fargo_logo.svg.png" },
{ abrev: "ADBE", name: "Adobe Inc.", commonName: "Adobe", link: "https://www.adobe.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Adobe_logo.svg/1200px-Adobe_logo.svg.png" },
{ abrev: "PEP", name: "PepsiCo, Inc.", commonName: "PepsiCo", link: "https://www.pepsico.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/PepsiCo_logo.svg/1200px-PepsiCo_logo.svg.png" },
{ abrev: "UNH", name: "UnitedHealth Group Incorporated", commonName: "UnitedHealth", link: "https://www.unitedhealthgroup.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/UnitedHealth_Group_logo.svg/1200px-UnitedHealth_Group_logo.svg.png" },
{ abrev: "CARR", name: "Carrier Global Corporation", commonName: "Carrier", link: "https://www.carrierglobal.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Carrier_Global_logo.svg/1200px-Carrier_Global_logo.svg.png" },
{ abrev: "FUBO", name: "fuboTV Inc.", commonName: "fuboTV", link: "https://www.fubo.tv", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/FuboTV_logo_2023.svg/1200px-FuboTV_logo_2023.svg.png" },
{ abrev: "HCA", name: "HCA Healthcare, Inc.", commonName: "HCA Healthcare", link: "https://www.hcahealthcare.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/HCA_Healthcare_logo.svg/1200px-HCA_Healthcare_logo.svg.png" },
{ abrev: "TWTR", name: "Twitter, Inc. (Now X)", commonName: "X (formerly Twitter)", link: "https://www.x.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/X_logo_2023.svg/1200px-X_logo_2023.svg.png" },
{ abrev: "BILI", name: "Bilibili Inc.", commonName: "Bilibili", link: "https://www.bilibili.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bilibili_logo_2019.svg/1200px-Bilibili_logo_2019.svg.png" },
{ abrev: "RKT", name: "Rocket Companies, Inc.", commonName: "Rocket Companies", link: "https://www.rocketcompanies.com", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Rocket_Companies_logo.svg/1200px-Rocket_Companies_logo.svg.png" }
];