
  // Available company options
  export const companies = [
    { abrev: "AAPL", name: "Apple Inc.", link: "https://www.apple.com"},
    { abrev: "TSLA", name: "Tesla, Inc.", link: "https://www.tesla.com" },
    { abrev: "AMZN", name: "Amazon.com, Inc.", link: "https://www.amazon.com" },
    { abrev: "MSFT", name: "Microsoft Corporation", link: "https://www.microsoft.com" },
    { abrev: "NVDA", name: "NVIDIA Corporation", link: "https://www.nvidia.com" },
    { abrev: "GOOGL", name: "Alphabet Inc.", link: "https://www.abc.xyz" },
    { abrev: "META", name: "Meta Platforms, Inc.", link: "https://about.fb.com" },
    { abrev: "NFLX", name: "Netflix, Inc.", link: "https://www.netflix.com" },
    { abrev: "JPM", name: "JPMorgan Chase & Co.", link: "https://www.jpmorganchase.com" },
    { abrev: "V", name: "Visa Inc.", link: "https://www.visa.com" },
    { abrev: "BAC", name: "Bank of America Corporation", link: "https://www.bankofamerica.com" },
    { abrev: "AMD", name: "Advanced Micro Devices, Inc.", link: "https://www.amd.com" },
    { abrev: "PYPL", name: "PayPal Holdings, Inc.", link: "https://www.paypal.com" },
    { abrev: "DIS", name: "The Walt Disney Company", link: "https://www.thewaltdisneycompany.com" },
    { abrev: "T", name: "AT&T Inc.", link: "https://www.att.com" },
    { abrev: "PFE", name: "Pfizer Inc.", link: "https://www.pfizer.com" },
    { abrev: "COST", name: "Costco Wholesale Corporation", link: "https://www.costco.com" },
    { abrev: "INTC", name: "Intel Corporation", link: "https://www.intel.com" },
    { abrev: "KO", name: "The Coca-Cola Company", link: "https://www.coca-colacompany.com" },
    { abrev: "TGT", name: "Target Corporation", link: "https://www.target.com" },
    { abrev: "NKE", name: "NIKE, Inc.", link: "https://www.nike.com" },
    { abrev: "SPY", name: "SPDR S&P 500 ETF Trust", link: "https://www.ssga.com/us/en/institutional/etfs/funds/spdr-s-p-500-etf-trust-spy" },
    { abrev: "BA", name: "The Boeing Company", link: "https://www.boeing.com" },
    { abrev: "BABA", name: "Alibaba Group Holding Limited", link: "https://www.alibabagroup.com" },
    { abrev: "XOM", name: "Exxon Mobil Corporation", link: "https://corporate.exxonmobil.com" },
    { abrev: "WMT", name: "Walmart Inc.", link: "https://www.walmart.com" },
    { abrev: "GE", name: "General Electric Company", link: "https://www.ge.com" },
    { abrev: "CSCO", name: "Cisco Systems, Inc.", link: "https://www.cisco.com" },
    { abrev: "VZ", name: "Verizon Communications Inc.", link: "https://www.verizon.com" },
    { abrev: "JNJ", name: "Johnson & Johnson", link: "https://www.jnj.com" },
    { abrev: "CVX", name: "Chevron Corporation", link: "https://www.chevron.com" },
    { abrev: "PLTR", name: "Palantir Technologies Inc.", link: "https://www.palantir.com" },
    { abrev: "SQ", name: "Block, Inc.", link: "https://www.block.xyz" },
    { abrev: "SHOP", name: "Shopify Inc.", link: "https://www.shopify.com" },
    { abrev: "SBUX", name: "Starbucks Corporation", link: "https://www.starbucks.com" },
    { abrev: "SOFI", name: "SoFi Technologies, Inc.", link: "https://www.sofi.com" },
    { abrev: "HOOD", name: "Robinhood Markets, Inc.", link: "https://www.robinhood.com" },
    { abrev: "RBLX", name: "Roblox Corporation", link: "https://www.roblox.com" },
    { abrev: "SNAP", name: "Snap Inc.", link: "https://www.snap.com" },
    { abrev: "UBER", name: "Uber Technologies, Inc.", link: "https://www.uber.com" },
    { abrev: "FDX", name: "FedEx Corporation", link: "https://www.fedex.com" },
    { abrev: "ABBV", name: "AbbVie Inc.", link: "https://www.abbvie.com" },
    { abrev: "ETSY", name: "Etsy, Inc.", link: "https://www.etsy.com" },
    { abrev: "MRNA", name: "Moderna, Inc.", link: "https://www.modernatx.com" },
    { abrev: "LMT", name: "Lockheed Martin Corporation", link: "https://www.lockheedmartin.com" },
    { abrev: "GM", name: "General Motors Company", link: "https://investor.gm.com" },
    { abrev: "F", name: "Ford Motor Company", link: "https://www.ford.com" },
    { abrev: "RIVN", name: "Rivian Automotive, Inc.", link: "https://www.rivian.com" },
    { abrev: "LCID", name: "Lucid Group, Inc.", link: "https://www.lucidmotors.com" },
    { abrev: "CCL", name: "Carnival Corporation & plc", link: "https://www.carnivalcorp.com" },
    { abrev: "DAL", name: "Delta Air Lines, Inc.", link: "https://www.delta.com" },
    { abrev: "UAL", name: "United Airlines Holdings, Inc.", link: "https://www.united.com" },
    { abrev: "AAL", name: "American Airlines Group Inc.", link: "https://www.aa.com" },
    { abrev: "TSM", name: "Taiwan Semiconductor Manufacturing Company Limited", link: "https://www.tsmc.com" },
    { abrev: "SONY", name: "Sony Group Corporation", link: "https://www.sony.com" },
    { abrev: "ET", name: "Energy Transfer LP", link: "https://www.energytransfer.com" },
    { abrev: "NOK", name: "Nokia Corporation", link: "https://www.nokia.com" },
    { abrev: "MRO", name: "Marathon Oil Corporation", link: "https://www.marathonoil.com" },
    { abrev: "COIN", name: "Coinbase Global, Inc.", link: "https://www.coinbase.com" },
    { abrev: "SIRI", name: "Sirius XM Holdings Inc.", link: "https://www.siriusxm.com" },
    { abrev: "RIOT", name: "Riot Platforms, Inc.", link: "https://www.riotplatforms.com" },
    { abrev: "CPRX", name: "Catalyst Pharmaceuticals, Inc.", link: "https://www.catalystpharma.com" },
    { abrev: "VWO", name: "Vanguard FTSE Emerging Markets ETF", link: "https://www.vanguard.com" },
    { abrev: "SPYG", name: "SPDR Portfolio S&P 500 Growth ETF", link: "https://www.ssga.com/us/en/institutional/etfs/funds/spdr-portfolio-s-p-500-growth-etf-spyg" },
    { abrev: "ROKU", name: "Roku, Inc.", link: "https://www.roku.com" },
    { abrev: "VIAC", name: "Paramount Global", link: "https://www.paramount.com" },
    { abrev: "ATVI", name: "Activision Blizzard, Inc.", link: "https://www.activisionblizzard.com" },
    { abrev: "BIDU", name: "Baidu, Inc.", link: "https://www.baidu.com" },
    { abrev: "DOCU", name: "DocuSign, Inc.", link: "https://www.docusign.com" },
    { abrev: "ZM", name: "Zoom Video Communications, Inc.", link: "https://www.zoom.us" },
    { abrev: "PINS", name: "Pinterest, Inc.", link: "https://www.pinterest.com" },
    { abrev: "TLRY", name: "Tilray Brands, Inc.", link: "https://www.tilray.com" },
    { abrev: "WBA", name: "Walgreens Boots Alliance, Inc.", link: "https://www.walgreensbootsalliance.com" },
    { abrev: "MGM", name: "MGM Resorts International", link: "https://www.mgmresorts.com" },
    { abrev: "NIO", name: "NIO Inc.", link: "https://www.nio.com" },
    { abrev: "C", name: "Citigroup Inc.", link: "https://www.citigroup.com" },
    { abrev: "GS", name: "The Goldman Sachs Group, Inc.", link: "https://www.goldmansachs.com" },
    { abrev: "WFC", name: "Wells Fargo & Company", link: "https://www.wellsfargo.com" },
    { abrev: "ADBE", name: "Adobe Inc.", link: "https://www.adobe.com" },
    { abrev: "PEP", name: "PepsiCo, Inc.", link: "https://www.pepsico.com" },
    { abrev: "UNH", name: "UnitedHealth Group Incorporated", link: "https://www.unitedhealthgroup.com" },
    { abrev: "CARR", name: "Carrier Global Corporation", link: "https://www.carrierglobal.com" },
    { abrev: "FUBO", name: "fuboTV Inc.", link: "https://www.fubo.tv" },
    { abrev: "HCA", name: "HCA Healthcare, Inc.", link: "https://www.hcahealthcare.com" },
    { abrev: "TWTR", name: "Twitter, Inc.", link: "https://www.twitter.com" },
    { abrev: "BILI", name: "Bilibili Inc.", link: "https://www.bilibili.com" },
    { abrev: "RKT", name: "Rocket Companies, Inc.", link: "https://www.rocketcompanies.com" }
  ];
  
