import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('API Key:', process.env.NEXT_PUBLIC_FIREBASE_API_KEY);
  return (
    <html lang="en">
      <body>
        <Navbar title="Business Health" />
        {children}
      </body>
    </html>
  );
}
