import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import RedirectAuth from "./components/RedirectAuth";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar title="Business Health" />
        <RedirectAuth />
        {children}
      </body>
    </html>
  );
}
